server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 1G;
    client_body_timeout 60s;
    keepalive_timeout 65s;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/livewire/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        
        # Parametri standard FastCGI
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        
        # INIEZIONE DEGLI HEADER PROXY DIRETTAMENTE A PHP-FPM
        # Questo forza Laravel a riconoscere l'IP e la porta (8088) originali richiesti dal browser
        #fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        #fastcgi_param HTTP_X_FORWARDED_HOST $host:$server_port;
        #fastcgi_param HTTP_X_FORWARDED_PORT $server_port;
        #fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;

        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_PORT $http_x_forwarded_port;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;

        resolver 127.0.0.11 ipv6=off valid=10s;
        set $php_fpm_upstream api_app:9000;
        fastcgi_pass $php_fpm_upstream;

        fastcgi_read_timeout 120s;
        
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
}
