FROM php:8.5-fpm-alpine
# hadolint ignore=DL3018
RUN apk add --no-cache icu-dev libpq-dev libzip-dev zip unzip git postgresql-client && \
	docker-php-ext-install bcmath intl pdo_pgsql zip
# hadolint ignore=DL3006
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
# hadolint ignore=DL3002
USER www-data
CMD ["php-fpm"]

